/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      // ── Colours ────────────────────────────────────────────
      colors: {
        brand: {
          50:  'var(--color-brand-50)',
          100: 'var(--color-brand-100)',
          200: 'var(--color-brand-200)',
          300: 'var(--color-brand-300)',
          400: 'var(--color-brand-400)',
          500: 'var(--color-brand-500)',
          600: 'var(--color-brand-600)',
          700: 'var(--color-brand-700)',
          800: 'var(--color-brand-800)',
          900: 'var(--color-brand-900)',
          950: 'var(--color-brand-950)',
        },
        neutral: {
          0:   'var(--color-neutral-0)',
          50:  'var(--color-neutral-50)',
          100: 'var(--color-neutral-100)',
          200: 'var(--color-neutral-200)',
          300: 'var(--color-neutral-300)',
          400: 'var(--color-neutral-400)',
          500: 'var(--color-neutral-500)',
          600: 'var(--color-neutral-600)',
          700: 'var(--color-neutral-700)',
          800: 'var(--color-neutral-800)',
          900: 'var(--color-neutral-900)',
          950: 'var(--color-neutral-950)',
        },
        success: {
          50:  'var(--color-success-50)',
          100: 'var(--color-success-100)',
          200: 'var(--color-success-200)',
          300: 'var(--color-success-300)',
          400: 'var(--color-success-400)',
          500: 'var(--color-success-500)',
          600: 'var(--color-success-600)',
          700: 'var(--color-success-700)',
          800: 'var(--color-success-800)',
          900: 'var(--color-success-900)',
        },
        warning: {
          50:  'var(--color-warning-50)',
          100: 'var(--color-warning-100)',
          200: 'var(--color-warning-200)',
          300: 'var(--color-warning-300)',
          400: 'var(--color-warning-400)',
          500: 'var(--color-warning-500)',
          600: 'var(--color-warning-600)',
          700: 'var(--color-warning-700)',
          800: 'var(--color-warning-800)',
          900: 'var(--color-warning-900)',
        },
        error: {
          50:  'var(--color-error-50)',
          100: 'var(--color-error-100)',
          200: 'var(--color-error-200)',
          300: 'var(--color-error-300)',
          400: 'var(--color-error-400)',
          500: 'var(--color-error-500)',
          600: 'var(--color-error-600)',
          700: 'var(--color-error-700)',
          800: 'var(--color-error-800)',
          900: 'var(--color-error-900)',
        },
        info: {
          50:  'var(--color-info-50)',
          100: 'var(--color-info-100)',
          200: 'var(--color-info-200)',
          300: 'var(--color-info-300)',
          400: 'var(--color-info-400)',
          500: 'var(--color-info-500)',
          600: 'var(--color-info-600)',
          700: 'var(--color-info-700)',
        },
        // Semantic aliases
        primary: 'var(--color-primary)',
        surface: 'var(--color-surface)',
        border: 'var(--color-border)',
      },

      // ── Spacing ─────────────────────────────────────────────
      spacing: {
        px:    'var(--spacing-px)',
        '0.5': 'var(--spacing-0-5)',
        1:     'var(--spacing-1)',
        '1.5': 'var(--spacing-1-5)',
        2:     'var(--spacing-2)',
        '2.5': 'var(--spacing-2-5)',
        3:     'var(--spacing-3)',
        '3.5': 'var(--spacing-3-5)',
        4:     'var(--spacing-4)',
        5:     'var(--spacing-5)',
        6:     'var(--spacing-6)',
        7:     'var(--spacing-7)',
        8:     'var(--spacing-8)',
        9:     'var(--spacing-9)',
        10:    'var(--spacing-10)',
        11:    'var(--spacing-11)',
        12:    'var(--spacing-12)',
        14:    'var(--spacing-14)',
        16:    'var(--spacing-16)',
        20:    'var(--spacing-20)',
        24:    'var(--spacing-24)',
        28:    'var(--spacing-28)',
        32:    'var(--spacing-32)',
        36:    'var(--spacing-36)',
        40:    'var(--spacing-40)',
        44:    'var(--spacing-44)',
        48:    'var(--spacing-48)',
        52:    'var(--spacing-52)',
        56:    'var(--spacing-56)',
        60:    'var(--spacing-60)',
        64:    'var(--spacing-64)',
        72:    'var(--spacing-72)',
        80:    'var(--spacing-80)',
        96:    'var(--spacing-96)',
      },

      // ── Border Radius ────────────────────────────────────────
      borderRadius: {
        none: 'var(--radius-none)',
        sm:   'var(--radius-sm)',
        DEFAULT: 'var(--radius-base)',
        md:   'var(--radius-md)',
        lg:   'var(--radius-lg)',
        xl:   'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        '3xl': 'var(--radius-3xl)',
        full: 'var(--radius-full)',
      },

      // ── Box Shadows ──────────────────────────────────────────
      boxShadow: {
        none:  'var(--shadow-none)',
        xs:    'var(--shadow-xs)',
        sm:    'var(--shadow-sm)',
        DEFAULT: 'var(--shadow-md)',
        md:    'var(--shadow-md)',
        lg:    'var(--shadow-lg)',
        xl:    'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        inner: 'var(--shadow-inner)',
        focus: 'var(--shadow-focus)',
      },

      // ── Typography ───────────────────────────────────────────
      fontFamily: {
        sans: 'var(--font-family-sans)',
        mono: 'var(--font-family-mono)',
      },
      fontSize: {
        xs:   'var(--font-size-xs)',
        sm:   'var(--font-size-sm)',
        base: 'var(--font-size-base)',
        lg:   'var(--font-size-lg)',
        xl:   'var(--font-size-xl)',
        '2xl': 'var(--font-size-2xl)',
        '3xl': 'var(--font-size-3xl)',
        '4xl': 'var(--font-size-4xl)',
        '5xl': 'var(--font-size-5xl)',
      },
      fontWeight: {
        light:     'var(--font-weight-light)',
        normal:    'var(--font-weight-normal)',
        medium:    'var(--font-weight-medium)',
        semibold:  'var(--font-weight-semibold)',
        bold:      'var(--font-weight-bold)',
        extrabold: 'var(--font-weight-extrabold)',
      },
      lineHeight: {
        none:    'var(--line-height-none)',
        tight:   'var(--line-height-tight)',
        snug:    'var(--line-height-snug)',
        normal:  'var(--line-height-normal)',
        relaxed: 'var(--line-height-relaxed)',
        loose:   'var(--line-height-loose)',
      },

      // ── Transitions ──────────────────────────────────────────
      transitionDuration: {
        fast:   '150',
        base:   '200',
        slow:   '300',
        slower: '500',
      },

      // ── Z-Index ───────────────────────────────────────────────
      zIndex: {
        base:     'var(--z-index-base)',
        raised:   'var(--z-index-raised)',
        dropdown: 'var(--z-index-dropdown)',
        sticky:   'var(--z-index-sticky)',
        overlay:  'var(--z-index-overlay)',
        modal:    'var(--z-index-modal)',
        toast:    'var(--z-index-toast)',
        tooltip:  'var(--z-index-tooltip)',
      },
    },
  },
  plugins: [],
};
